---
- name: Backup Cisco Device Config
  hosts: switches
  gather_facts: false
  connection: network_cli
  tasks:
    - name: Backup switch configurations
      ios_config:
        backup: true
        backup_options:
          dir_path: "/opt/ansible/cisco-configs"


# 10.234.3.1 ansible_network_os=cisco.ios.ios
# ansible-playbook ansible-configbackup.yml -u cisco -k