
#    ansible-vault create passwords.yml
#    makefile passwords.yml
#    ansible_ssh_pass: cisco
#    ansible_become_password: cisco123
#    save as .yml

#    ansible-playbook --ask-vault-pass cisco-switch-dns.yml

---
- name: Configure DNS on Cisco switch
  hosts: switches
  become: yes
  vars_files:
    - passwords.yml
  tasks:
    - name: Configure DNS name servers
      cisco.ios.ios_dns:
        name_servers:
          - 8.8.8.8
          - 1.1.1.1
      register: dns_result

    - name: Save configuration
      cisco.ios.ios_command:
        commands:
          - write memory
      register: save_result

    - name: Log output to file
      copy:
        content: "{{ dns_result.stdout[0] }} {{ save_result.stdout[0] }}"
        dest: "cisco-switch-dns"
