

#       ansible-playbook precheck.yml
#       edit /etc/ansible/hosts "servers"
#       ansible-playbook precheck.yml

---
- name: Precheck before configuration changes
  hosts: servers
  gather_facts: no
  tasks:
    - name: Ping all hosts
      block:
        - name: Ping host
          ping:
            count: 5
          register: ping_result

        - name: Save ping output to file
          copy:
            content: "{{ ping_result.stdout_lines | join('\n') }}"
            dest: "/home/admin/logs/precheck-updown"
